export const LOAD_GAMES_SUCCESS = "LOAD_GAMES_SUCCESS";
export const LOAD_GAME_DETAILS_SUCCESS = "LOAD_GAME_DETAILS_SUCCESS";
export const API_SUCCESS = "API_SUCCESS";
export const API_ERROR = "API_ERROR";
export const SET_LOADER = "SET_LOADER";
export const LOGOUT = "LOGOUT";