export const GET_GAMES_SUCCESS = "GET_GAMES_SUCCESS";
export const LOGOUT_SUCCESS = "LOGOUT_SUCCESS";
export const LOGIN_SUCCESS = "LOGIN_SUCCESS";
export const ADD_USER_SUCCESS = "ADD_USER_SUCCESS"
export const GET_WAGERS_SUCCESS = "GET_WAGERS_SUCCESS";
export const ADD_WAGER_SUCCESS = "ADD_WAGERS_SUCCESS";
export const GET_ALL_GAMES_SUCCESS = "GET_ALL_GAMES_SUCCESS"
